# Generated by Django 3.0.1 on 2020-02-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpiManager',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('value', models.FloatField(verbose_name='value')),
                ('publicDate', models.DateField(blank=True, null=True, verbose_name='publicDate')),
            ],
            options={
                'db_table': 'cpi',
            },
        ),
    ]
