# Generated by Django 3.0.7 on 2020-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpiManager',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('value', models.FloatField(verbose_name='value')),
                ('publicDate', models.DateField(blank=True, null=True, verbose_name='publicDate')),
            ],
            options={
                'db_table': 'cpi',
            },
        ),
        migrations.CreateModel(
            name='MoneySupplyDb',
            fields=[
                ('time', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='time')),
                ('m2Value', models.FloatField(verbose_name='m2Value')),
                ('m2YOY', models.FloatField(verbose_name='m2YOY')),
                ('m1Value', models.FloatField(verbose_name='m1Value')),
                ('m1YOY', models.FloatField(verbose_name='m1YOY')),
                ('m0Value', models.FloatField(verbose_name='m0Value')),
                ('m0YOY', models.FloatField(verbose_name='m0YOY')),
                ('publicDate', models.DateField(blank=True, null=True, verbose_name='publicDate')),
            ],
            options={
                'db_table': 'MoneySupply',
            },
        ),
        migrations.CreateModel(
            name='PmiManager',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('manufacturingValue', models.FloatField(verbose_name='manufacturingValue')),
                ('nonManufacturingValue', models.FloatField(verbose_name='nonManufacturingValue')),
                ('publicDate', models.DateField(blank=True, null=True, verbose_name='publicDate')),
            ],
            options={
                'db_table': 'pmi',
            },
        ),
        migrations.CreateModel(
            name='PpiManager',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('value', models.FloatField(verbose_name='value')),
                ('publicDate', models.DateField(blank=True, null=True, verbose_name='publicDate')),
            ],
            options={
                'db_table': 'ppi',
            },
        ),
        migrations.CreateModel(
            name='ReserveRequirementManager',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('bigFinancialInstitutionsValue', models.FloatField(verbose_name='bigFinancialInstitutionsValue')),
                ('smallMediumFinancialInstitutionsValue', models.FloatField(verbose_name='smallMediumFinancialInstitutionsValue')),
                ('publicDate', models.DateField(blank=True, null=True, verbose_name='publicDate')),
            ],
            options={
                'db_table': 'reserveRequirement',
            },
        ),
        migrations.CreateModel(
            name='stockLimitDown',
            fields=[
                ('trade_date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('ts_code', models.CharField(max_length=10, verbose_name='ts_code')),
                ('ts_name', models.CharField(max_length=10, verbose_name='ts_name')),
                ('close', models.FloatField(verbose_name='close')),
                ('pct_chg', models.FloatField(verbose_name='pct_chg')),
                ('amp', models.FloatField(verbose_name='amp')),
                ('fc_ratio', models.FloatField(verbose_name='fc_ratio')),
                ('fl_ratio', models.FloatField(verbose_name='fl_ratio')),
                ('fd_amount', models.FloatField(verbose_name='fd_amount')),
                ('first_time', models.TimeField(verbose_name='first_time')),
                ('last_time', models.TimeField(verbose_name='last_time')),
                ('open_times', models.IntegerField(verbose_name='open_times')),
                ('strth', models.FloatField(verbose_name='strth')),
            ],
            options={
                'db_table': 'stockLimitDown',
            },
        ),
        migrations.CreateModel(
            name='StockLimitUp',
            fields=[
                ('trade_date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('ts_code', models.CharField(max_length=10, verbose_name='ts_code')),
                ('ts_name', models.CharField(max_length=10, verbose_name='ts_name')),
                ('close', models.FloatField(verbose_name='close')),
                ('pct_chg', models.FloatField(verbose_name='pct_chg')),
                ('amp', models.FloatField(verbose_name='amp')),
                ('fc_ratio', models.FloatField(verbose_name='fc_ratio')),
                ('fl_ratio', models.FloatField(verbose_name='fl_ratio')),
                ('fd_amount', models.FloatField(verbose_name='fd_amount')),
                ('first_time', models.TimeField(verbose_name='first_time')),
                ('last_time', models.TimeField(verbose_name='last_time')),
                ('open_times', models.IntegerField(verbose_name='open_times')),
                ('strth', models.FloatField(verbose_name='strth')),
            ],
            options={
                'db_table': 'stockLimitUp',
            },
        ),
    ]
