# Generated by Django 3.0.7 on 2020-07-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stockLimitDown',
        ),
        migrations.DeleteModel(
            name='StockLimitUp',
        ),
    ]
