# Generated by Django 3.0.1 on 2020-02-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CpiManager',
        ),
    ]
