# Generated by Django 3.0.7 on 2020-07-12 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0003_stocklimitdown_stocklimitup'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklimitdown',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklimitup',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocklimitdown',
            name='trade_date',
            field=models.CharField(max_length=8, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='stocklimitup',
            name='trade_date',
            field=models.CharField(max_length=8, verbose_name='date'),
        ),
    ]
