# Generated by Django 3.0.1 on 2020-02-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0003_cpimanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PpiManager',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('value', models.FloatField(verbose_name='value')),
                ('publicDate', models.DateField(blank=True, null=True, verbose_name='publicDate')),
            ],
            options={
                'db_table': 'ppi',
            },
        ),
    ]
