# Generated by Django 3.0.1 on 2020-02-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0004_ppimanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveRequirementManager',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('bigFinancialInstitutionsValue', models.FloatField(verbose_name='bigFinancialInstitutionsValue')),
                ('smallMediumFinancialInstitutionsValue', models.FloatField(verbose_name='smallMediumFinancialInstitutionsValue')),
                ('publicDate', models.DateField(blank=True, null=True, verbose_name='publicDate')),
            ],
            options={
                'db_table': 'reserveRequirement',
            },
        ),
    ]
