# Generated by Django 3.0.1 on 2020-02-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0005_reserverequirementmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmiManager',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('manufacturingValue', models.FloatField(verbose_name='manufacturingValue')),
                ('nonManufacturingValue', models.FloatField(verbose_name='nonManufacturingValue')),
                ('publicDate', models.DateField(blank=True, null=True, verbose_name='publicDate')),
            ],
            options={
                'db_table': 'pmi',
            },
        ),
    ]
