# Generated by Django 3.0.7 on 2020-07-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0008_stocklimitdown_stocklimitup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklimitdown',
            name='amp',
            field=models.FloatField(blank=True, null=True, verbose_name='amp'),
        ),
        migrations.AlterField(
            model_name='stocklimitdown',
            name='fc_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='fc_ratio'),
        ),
        migrations.AlterField(
            model_name='stocklimitdown',
            name='fd_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='fd_amount'),
        ),
        migrations.AlterField(
            model_name='stocklimitdown',
            name='first_time',
            field=models.TimeField(blank=True, null=True, verbose_name='first_time'),
        ),
        migrations.AlterField(
            model_name='stocklimitdown',
            name='fl_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='fl_ratio'),
        ),
        migrations.AlterField(
            model_name='stocklimitdown',
            name='last_time',
            field=models.TimeField(blank=True, null=True, verbose_name='last_time'),
        ),
        migrations.AlterField(
            model_name='stocklimitdown',
            name='open_times',
            field=models.IntegerField(blank=True, null=True, verbose_name='open_times'),
        ),
        migrations.AlterField(
            model_name='stocklimitdown',
            name='pct_chg',
            field=models.FloatField(blank=True, null=True, verbose_name='pct_chg'),
        ),
        migrations.AlterField(
            model_name='stocklimitdown',
            name='strth',
            field=models.FloatField(blank=True, null=True, verbose_name='strth'),
        ),
        migrations.AlterField(
            model_name='stocklimitup',
            name='amp',
            field=models.FloatField(blank=True, null=True, verbose_name='amp'),
        ),
        migrations.AlterField(
            model_name='stocklimitup',
            name='fc_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='fc_ratio'),
        ),
        migrations.AlterField(
            model_name='stocklimitup',
            name='fd_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='fd_amount'),
        ),
        migrations.AlterField(
            model_name='stocklimitup',
            name='first_time',
            field=models.TimeField(blank=True, null=True, verbose_name='first_time'),
        ),
        migrations.AlterField(
            model_name='stocklimitup',
            name='fl_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='fl_ratio'),
        ),
        migrations.AlterField(
            model_name='stocklimitup',
            name='last_time',
            field=models.TimeField(blank=True, null=True, verbose_name='last_time'),
        ),
        migrations.AlterField(
            model_name='stocklimitup',
            name='open_times',
            field=models.IntegerField(blank=True, null=True, verbose_name='open_times'),
        ),
        migrations.AlterField(
            model_name='stocklimitup',
            name='pct_chg',
            field=models.FloatField(blank=True, null=True, verbose_name='pct_chg'),
        ),
        migrations.AlterField(
            model_name='stocklimitup',
            name='strth',
            field=models.FloatField(blank=True, null=True, verbose_name='strth'),
        ),
    ]
