# Generated by Django 3.0.7 on 2020-07-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0009_auto_20200712_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumOfStockLimitUpDown',
            fields=[
                ('trade_date', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='date')),
                ('NumOfLimitUp', models.IntegerField(blank=True, null=True, verbose_name='NumOfLimitUp')),
                ('NumOfLimitDown', models.IntegerField(blank=True, null=True, verbose_name='NumOfLimitDown')),
            ],
            options={
                'db_table': 'numOfStockLimitUpDown',
            },
        ),
    ]
