# Generated by Django 3.0.7 on 2020-07-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0010_numofstocklimitupdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryCode', models.CharField(max_length=10, verbose_name='industryCode')),
                ('industryName', models.CharField(blank=True, max_length=16, null=True, verbose_name='industryName')),
                ('industryLevel', models.CharField(blank=True, max_length=2, null=True, verbose_name='industryLevel')),
            ],
            options={
                'db_table': 'industryClassify',
            },
        ),
    ]
