# Generated by Django 3.0.7 on 2020-07-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0012_auto_20200726_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklistofdustryclassify',
            name='industryCode',
            field=models.CharField(max_length=10, verbose_name='industryCode'),
        ),
        migrations.AlterField(
            model_name='stocklistofdustryclassify',
            name='stockCode',
            field=models.CharField(max_length=10, unique=True, verbose_name='stockCode'),
        ),
    ]
