# Generated by Django 3.0.7 on 2020-10-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0016_stocklistofdustryclassify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockListOfdustryClassify',
        ),
    ]
