document.writeln("<!-- Main navbar -->");
document.writeln("	<div class=\'navbar navbar-default header-highlight\'>");
document.writeln("		<div class=\'navbar-header\'>");
document.writeln("			<a class=\'navbar-brand\' href=\'index.html\'><img src=\'/static/assets/images/logo_light.png\' alt=\'\'></a>");
document.writeln("");
document.writeln("			<ul class=\'nav navbar-nav pull-right visible-xs-block\'>");
document.writeln("				<li><a data-toggle=\'collapse\' data-target=\'#navbar-mobile\'><i class=\'icon-tree5\'></i></a></li>");
document.writeln("				<li><a class=\'sidebar-mobile-main-toggle\'><i class=\'icon-paragraph-justify3\'></i></a></li>");
document.writeln("				<li><a class=\'sidebar-mobile-opposite-toggle\'><i class=\'icon-menu\'></i></a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("");
document.writeln("		<div class=\'navbar-collapse collapse\' id=\'navbar-mobile\'>");
document.writeln("			<ul class=\'nav navbar-nav\'>");
document.writeln("				<li>");
document.writeln("					<a class=\'sidebar-control sidebar-main-hide hidden-xs\' data-popup=\'tooltip\' title=\'Hide main\' data-placement=\'bottom\' data-container=\'body\'>");
document.writeln("						<i class=\'icon-paragraph-justify3\'></i>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				");
document.writeln("				<li>");
document.writeln("					<a class=\'sidebar-control sidebar-opposite-fix hidden-xs\' data-popup=\'tooltip\' title=\'Opposite - fix main\' data-placement=\'bottom\' data-container=\'body\'>");
document.writeln("						<i class=\'icon-lan3\'></i>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("");
document.writeln("				<li class=\'dropdown\'>");
document.writeln("					<a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("						<i class=\'icon-git-compare\'></i>");
document.writeln("						<span class=\'visible-xs-inline-block position-right\'>Git updates</span>");
document.writeln("						<span class=\'badge bg-warning-400\'>9</span>");
document.writeln("					</a>");
document.writeln("					");
document.writeln("					<div class=\'dropdown-menu dropdown-content\'>");
document.writeln("						<div class=\'dropdown-content-heading\'>");
document.writeln("							Git updates");
document.writeln("							<ul class=\'icons-list\'>");
document.writeln("								<li><a href=\'#\'><i class=\'icon-sync\'></i></a></li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("");
document.writeln("						<ul class=\'media-list dropdown-content-body width-350\'>");
document.writeln("							<li class=\'media\'>");
document.writeln("								<div class=\'media-left\'>");
document.writeln("									<a href=\'#\' class=\'btn border-primary text-primary btn-flat btn-rounded btn-icon btn-sm\'><i class=\'icon-git-pull-request\'></i></a>");
document.writeln("								</div>");
document.writeln("");
document.writeln("								<div class=\'media-body\'>");
document.writeln("									Drop the IE <a href=\'#\'>specific hacks</a> for temporal inputs");
document.writeln("									<div class=\'media-annotation\'>4 minutes ago</div>");
document.writeln("								</div>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'media\'>");
document.writeln("								<div class=\'media-left\'>");
document.writeln("									<a href=\'#\' class=\'btn border-warning text-warning btn-flat btn-rounded btn-icon btn-sm\'><i class=\'icon-git-commit\'></i></a>");
document.writeln("								</div>");
document.writeln("								");
document.writeln("								<div class=\'media-body\'>");
document.writeln("									Add full font overrides for popovers and tooltips");
document.writeln("									<div class=\'media-annotation\'>36 minutes ago</div>");
document.writeln("								</div>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'media\'>");
document.writeln("								<div class=\'media-left\'>");
document.writeln("									<a href=\'#\' class=\'btn border-info text-info btn-flat btn-rounded btn-icon btn-sm\'><i class=\'icon-git-branch\'></i></a>");
document.writeln("								</div>");
document.writeln("								");
document.writeln("								<div class=\'media-body\'>");
document.writeln("									<a href=\'#\'>Chris Arney</a> created a new <span class=\'text-semibold\'>Design</span> branch");
document.writeln("									<div class=\'media-annotation\'>2 hours ago</div>");
document.writeln("								</div>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'media\'>");
document.writeln("								<div class=\'media-left\'>");
document.writeln("									<a href=\'#\' class=\'btn border-success text-success btn-flat btn-rounded btn-icon btn-sm\'><i class=\'icon-git-merge\'></i></a>");
document.writeln("								</div>");
document.writeln("								");
document.writeln("								<div class=\'media-body\'>");
document.writeln("									<a href=\'#\'>Eugene Kopyov</a> merged <span class=\'text-semibold\'>Master</span> and <span class=\'text-semibold\'>Dev</span> branches");
document.writeln("									<div class=\'media-annotation\'>Dec 18, 18:36</div>");
document.writeln("								</div>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'media\'>");
document.writeln("								<div class=\'media-left\'>");
document.writeln("									<a href=\'#\' class=\'btn border-primary text-primary btn-flat btn-rounded btn-icon btn-sm\'><i class=\'icon-git-pull-request\'></i></a>");
document.writeln("								</div>");
document.writeln("								");
document.writeln("								<div class=\'media-body\'>");
document.writeln("									Have Carousel ignore keyboard events");
document.writeln("									<div class=\'media-annotation\'>Dec 12, 05:46</div>");
document.writeln("								</div>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("");
document.writeln("						<div class=\'dropdown-content-footer\'>");
document.writeln("							<a href=\'#\' data-popup=\'tooltip\' title=\'All activity\'><i class=\'icon-menu display-block\'></i></a>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("");
document.writeln("			<p class=\'navbar-text\'>");
document.writeln("				<span class=\'label bg-success\'>Online</span>");
document.writeln("			</p>");
document.writeln("");
document.writeln("			<div class=\'navbar-right\'>");
document.writeln("				<ul class=\'nav navbar-nav\'>");
document.writeln("					<li class=\'dropdown\'>");
document.writeln("						<a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("							<i class=\'icon-people\'></i>");
document.writeln("							<span class=\'visible-xs-inline-block position-right\'>Users</span>");
document.writeln("						</a>");
document.writeln("						");
document.writeln("						<div class=\'dropdown-menu dropdown-content\'>");
document.writeln("							<div class=\'dropdown-content-heading\'>");
document.writeln("								Users online");
document.writeln("								<ul class=\'icons-list\'>");
document.writeln("									<li><a href=\'#\'><i class=\'icon-gear\'></i></a></li>");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("");
document.writeln("							<ul class=\'media-list dropdown-content-body width-300\'>");
document.writeln("								<li class=\'media\'>");
document.writeln("									<div class=\'media-left\'><img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'></div>");
document.writeln("									<div class=\'media-body\'>");
document.writeln("										<a href=\'#\' class=\'media-heading text-semibold\'>DOWNLOADED FROM THEMELOCK.COM</a>");
document.writeln("										<span class=\'display-block text-muted text-size-small\'>Lead web developer</span>");
document.writeln("									</div>");
document.writeln("									<div class=\'media-right media-middle\'><span class=\'status-mark border-success\'></span></div>");
document.writeln("								</li>");
document.writeln("");
document.writeln("								<li class=\'media\'>");
document.writeln("									<div class=\'media-left\'><img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'></div>");
document.writeln("									<div class=\'media-body\'>");
document.writeln("										<a href=\'#\' class=\'media-heading text-semibold\'>Will Brason</a>");
document.writeln("										<span class=\'display-block text-muted text-size-small\'>Marketing manager</span>");
document.writeln("									</div>");
document.writeln("									<div class=\'media-right media-middle\'><span class=\'status-mark border-danger\'></span></div>");
document.writeln("								</li>");
document.writeln("");
document.writeln("								<li class=\'media\'>");
document.writeln("									<div class=\'media-left\'><img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'></div>");
document.writeln("									<div class=\'media-body\'>");
document.writeln("										<a href=\'#\' class=\'media-heading text-semibold\'>Hanna Walden</a>");
document.writeln("										<span class=\'display-block text-muted text-size-small\'>Project manager</span>");
document.writeln("									</div>");
document.writeln("									<div class=\'media-right media-middle\'><span class=\'status-mark border-success\'></span></div>");
document.writeln("								</li>");
document.writeln("");
document.writeln("								<li class=\'media\'>");
document.writeln("									<div class=\'media-left\'><img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'></div>");
document.writeln("									<div class=\'media-body\'>");
document.writeln("										<a href=\'#\' class=\'media-heading text-semibold\'>Dori Laperriere</a>");
document.writeln("										<span class=\'display-block text-muted text-size-small\'>Business developer</span>");
document.writeln("									</div>");
document.writeln("									<div class=\'media-right media-middle\'><span class=\'status-mark border-warning-300\'></span></div>");
document.writeln("								</li>");
document.writeln("");
document.writeln("								<li class=\'media\'>");
document.writeln("									<div class=\'media-left\'><img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'></div>");
document.writeln("									<div class=\'media-body\'>");
document.writeln("										<a href=\'#\' class=\'media-heading text-semibold\'>Vanessa Aurelius</a>");
document.writeln("										<span class=\'display-block text-muted text-size-small\'>UX expert</span>");
document.writeln("									</div>");
document.writeln("									<div class=\'media-right media-middle\'><span class=\'status-mark border-grey-400\'></span></div>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("");
document.writeln("							<div class=\'dropdown-content-footer\'>");
document.writeln("								<a href=\'#\' data-popup=\'tooltip\' title=\'All users\'><i class=\'icon-menu display-block\'></i></a>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("					</li>");
document.writeln("");
document.writeln("					<li class=\'dropdown\'>");
document.writeln("						<a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("							<i class=\'icon-bubbles4\'></i>");
document.writeln("							<span class=\'visible-xs-inline-block position-right\'>Messages</span>");
document.writeln("							<span class=\'badge bg-warning-400\'>2</span>");
document.writeln("						</a>");
document.writeln("						");
document.writeln("						<div class=\'dropdown-menu dropdown-content width-350\'>");
document.writeln("							<div class=\'dropdown-content-heading\'>");
document.writeln("								Messages");
document.writeln("								<ul class=\'icons-list\'>");
document.writeln("									<li><a href=\'#\'><i class=\'icon-compose\'></i></a></li>");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("");
document.writeln("							<ul class=\'media-list dropdown-content-body\'>");
document.writeln("								<li class=\'media\'>");
document.writeln("									<div class=\'media-left\'>");
document.writeln("										<img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'>");
document.writeln("										<span class=\'badge bg-danger-400 media-badge\'>5</span>");
document.writeln("									</div>");
document.writeln("");
document.writeln("									<div class=\'media-body\'>");
document.writeln("										<a href=\'#\' class=\'media-heading\'>");
document.writeln("											<span class=\'text-semibold\'>James Alexander</span>");
document.writeln("											<span class=\'media-annotation pull-right\'>04:58</span>");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<span class=\'text-muted\'>who knows, maybe that would be the best thing for me...</span>");
document.writeln("									</div>");
document.writeln("								</li>");
document.writeln("");
document.writeln("								<li class=\'media\'>");
document.writeln("									<div class=\'media-left\'>");
document.writeln("										<img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'>");
document.writeln("										<span class=\'badge bg-danger-400 media-badge\'>4</span>");
document.writeln("									</div>");
document.writeln("");
document.writeln("									<div class=\'media-body\'>");
document.writeln("										<a href=\'#\' class=\'media-heading\'>");
document.writeln("											<span class=\'text-semibold\'>Margo Baker</span>");
document.writeln("											<span class=\'media-annotation pull-right\'>12:16</span>");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<span class=\'text-muted\'>That was something he was unable to do because...</span>");
document.writeln("									</div>");
document.writeln("								</li>");
document.writeln("");
document.writeln("								<li class=\'media\'>");
document.writeln("									<div class=\'media-left\'><img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'></div>");
document.writeln("									<div class=\'media-body\'>");
document.writeln("										<a href=\'#\' class=\'media-heading\'>");
document.writeln("											<span class=\'text-semibold\'>Jeremy Victorino</span>");
document.writeln("											<span class=\'media-annotation pull-right\'>22:48</span>");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<span class=\'text-muted\'>But that would be extremely strained and suspicious...</span>");
document.writeln("									</div>");
document.writeln("								</li>");
document.writeln("");
document.writeln("								<li class=\'media\'>");
document.writeln("									<div class=\'media-left\'><img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'></div>");
document.writeln("									<div class=\'media-body\'>");
document.writeln("										<a href=\'#\' class=\'media-heading\'>");
document.writeln("											<span class=\'text-semibold\'>Beatrix Diaz</span>");
document.writeln("											<span class=\'media-annotation pull-right\'>Tue</span>");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<span class=\'text-muted\'>What a strenuous career it is that I\'ve chosen...</span>");
document.writeln("									</div>");
document.writeln("								</li>");
document.writeln("");
document.writeln("								<li class=\'media\'>");
document.writeln("									<div class=\'media-left\'><img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'></div>");
document.writeln("									<div class=\'media-body\'>");
document.writeln("										<a href=\'#\' class=\'media-heading\'>");
document.writeln("											<span class=\'text-semibold\'>Richard Vango</span>");
document.writeln("											<span class=\'media-annotation pull-right\'>Mon</span>");
document.writeln("										</a>");
document.writeln("										");
document.writeln("										<span class=\'text-muted\'>Other travelling salesmen live a life of luxury...</span>");
document.writeln("									</div>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("");
document.writeln("							<div class=\'dropdown-content-footer\'>");
document.writeln("								<a href=\'#\' data-popup=\'tooltip\' title=\'All messages\'><i class=\'icon-menu display-block\'></i></a>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("					</li>");
document.writeln("");
document.writeln("					<li class=\'dropdown dropdown-user\'>");
document.writeln("						<a class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("							<img src=\'/static/assets/images/placeholder.jpg\' alt=\'\'>");
document.writeln("							<span>Victoria</span>");
document.writeln("							<i class=\'caret\'></i>");
document.writeln("						</a>");
document.writeln("");
document.writeln("						<ul class=\'dropdown-menu dropdown-menu-right\'>");
document.writeln("							<li><a href=\'#\'><i class=\'icon-user-plus\'></i> My profile</a></li>");
document.writeln("							<li><a href=\'#\'><i class=\'icon-coins\'></i> My balance</a></li>");
document.writeln("							<li><a href=\'#\'><span class=\'badge bg-blue pull-right\'>58</span> <i class=\'icon-comment-discussion\'></i> Messages</a></li>");
document.writeln("							<li class=\'divider\'></li>");
document.writeln("							<li><a href=\'#\'><i class=\'icon-cog5\'></i> Account settings</a></li>");
document.writeln("							<li><a href=\'#\'><i class=\'icon-switch2\'></i> Logout</a></li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!-- /main navbar -->");