document.writeln("			<!-- Main sidebar -->");
document.writeln("			<div class=\'sidebar sidebar-main\'>");
document.writeln("				<div class=\'sidebar-content\'>");
document.writeln("");
document.writeln("					<!-- User menu -->");
document.writeln("					<div class=\'sidebar-user\'>");
document.writeln("						<div class=\'category-content\'>");
document.writeln("							<div class=\'media\'>");
document.writeln("								<a href=\'#\' class=\'media-left\'><img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'></a>");
document.writeln("								<div class=\'media-body\'>");
document.writeln("									<span class=\'media-heading text-semibold\'>Victoria Baker</span>");
document.writeln("									<div class=\'text-size-mini text-muted\'>");
document.writeln("										<i class=\'icon-pin text-size-small\'></i> &nbsp;Santa Ana, CA");
document.writeln("									</div>");
document.writeln("								</div>");
document.writeln("");
document.writeln("								<div class=\'media-right media-middle\'>");
document.writeln("									<ul class=\'icons-list\'>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'><i class=\'icon-cog3\'></i></a>");
document.writeln("										</li>");
document.writeln("									</ul>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<!-- /user menu -->");
document.writeln("");
document.writeln("");
document.writeln("					<!-- Main navigation -->");
document.writeln("					<div class=\'sidebar-category sidebar-category-visible\'>");
document.writeln("						<div class=\'category-content no-padding\'>");
document.writeln("							<ul class=\'navigation navigation-main navigation-accordion\'>");
document.writeln("");
document.writeln("								<!-- Main -->");
document.writeln("								<li><a href=\'static/index.html\'><i class=\'icon-home4\'></i> <span>主页</span></a></li>");
document.writeln("								<li class=\'navigation-header\'><span>个股分析</span> <i class=\'icon-menu\' title=\'个股分析\'></i></li>");
document.writeln("								<li><a href=\'industries.html\'><i class=\'icon-stack2\'></i> <span>行业分析</span></a></li>");
document.writeln("");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-stack2\'></i> <span>Page layouts</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'layout_navbar_fixed.html\'>Fixed navbar</a></li>");
document.writeln("										<li><a href=\'layout_navbar_sidebar_fixed.html\'>Fixed navbar &amp; sidebar</a></li>");
document.writeln("										<li><a href=\'layout_sidebar_fixed_native.html\'>Fixed sidebar native scroll</a></li>");
document.writeln("										<li><a href=\'layout_navbar_hideable.html\'>Hideable navbar</a></li>");
document.writeln("										<li><a href=\'layout_navbar_hideable_sidebar.html\'>Hideable &amp; fixed sidebar</a></li>");
document.writeln("										<li><a href=\'layout_footer_fixed.html\'>Fixed footer</a></li>");
document.writeln("										<li class=\'navigation-divider\'></li>");
document.writeln("										<li><a href=\'boxed_default.html\'>Boxed with default sidebar</a></li>");
document.writeln("										<li><a href=\'boxed_mini.html\'>Boxed with mini sidebar</a></li>");
document.writeln("										<li><a href=\'boxed_full.html\'>Boxed full width</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-copy\'></i> <span>Layouts</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'../../layout_1/LTR/index.html\' id=\'layout1\'>Layout 1</a></li>");
document.writeln("										<li><a href=\'index.html\' id=\'layout2\'>Layout 2 <span class=\'label bg-warning-400\'>Current</span></a></li>");
document.writeln("										<li><a href=\'../../layout_3/LTR/index.html\' id=\'layout3\'>Layout 3</a></li>");
document.writeln("										<li><a href=\'../../layout_4/LTR/index.html\' id=\'layout4\'>Layout 4</a></li>");
document.writeln("										<li class=\'disabled\'><a href=\'../../layout_5/LTR/index.html\' id=\'layout5\'>Layout 5 <span class=\'label\'>Coming soon</span></a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-droplet2\'></i> <span>Color system</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'colors_primary.html\'>Primary palette</a></li>");
document.writeln("										<li><a href=\'colors_danger.html\'>Danger palette</a></li>");
document.writeln("										<li><a href=\'colors_success.html\'>Success palette</a></li>");
document.writeln("										<li><a href=\'colors_warning.html\'>Warning palette</a></li>");
document.writeln("										<li><a href=\'colors_info.html\'>Info palette</a></li>");
document.writeln("										<li class=\'navigation-divider\'></li>");
document.writeln("										<li><a href=\'colors_pink.html\'>Pink palette</a></li>");
document.writeln("										<li><a href=\'colors_violet.html\'>Violet palette</a></li>");
document.writeln("										<li><a href=\'colors_purple.html\'>Purple palette</a></li>");
document.writeln("										<li><a href=\'colors_indigo.html\'>Indigo palette</a></li>");
document.writeln("										<li><a href=\'colors_blue.html\'>Blue palette</a></li>");
document.writeln("										<li><a href=\'colors_teal.html\'>Teal palette</a></li>");
document.writeln("										<li><a href=\'colors_green.html\'>Green palette</a></li>");
document.writeln("										<li><a href=\'colors_orange.html\'>Orange palette</a></li>");
document.writeln("										<li><a href=\'colors_brown.html\'>Brown palette</a></li>");
document.writeln("										<li><a href=\'colors_grey.html\'>Grey palette</a></li>");
document.writeln("										<li><a href=\'colors_slate.html\'>Slate palette</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-stack\'></i> <span>Starter kit</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'starters/horizontal_nav.html\'>Horizontal navigation</a></li>");
document.writeln("										<li><a href=\'starters/1_col.html\'>1 column</a></li>");
document.writeln("										<li><a href=\'starters/2_col.html\'>2 columns</a></li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>3 columns</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'starters/3_col_dual.html\'>Dual sidebars</a></li>");
document.writeln("												<li><a href=\'starters/3_col_double.html\'>Double sidebars</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li><a href=\'starters/4_col.html\'>4 columns</a></li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Detached layout</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'starters/detached_left.html\'>Left sidebar</a></li>");
document.writeln("												<li><a href=\'starters/detached_right.html\'>Right sidebar</a></li>");
document.writeln("												<li><a href=\'starters/detached_sticky.html\'>Sticky sidebar</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li><a href=\'starters/layout_boxed.html\'>Boxed layout</a></li>");
document.writeln("										<li class=\'navigation-divider\'></li>");
document.writeln("										<li><a href=\'starters/layout_navbar_fixed_main.html\'>Fixed main navbar</a></li>");
document.writeln("										<li><a href=\'starters/layout_navbar_fixed_secondary.html\'>Fixed secondary navbar</a></li>");
document.writeln("										<li><a href=\'starters/layout_navbar_fixed_both.html\'>Both navbars fixed</a></li>");
document.writeln("										<li><a href=\'starters/layout_fixed.html\'>Fixed layout</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li><a href=\'changelog.html\'><i class=\'icon-list-unordered\'></i> <span>Changelog</span></a></li>");
document.writeln("								<!-- /main -->");
document.writeln("");
document.writeln("								<!-- Forms -->");
document.writeln("								<li class=\'navigation-header\'><span>Forms</span> <i class=\'icon-menu\' title=\'Forms\'></i></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-pencil3\'></i> <span>Form components</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'form_inputs_basic.html\'>Basic inputs</a></li>");
document.writeln("										<li><a href=\'form_checkboxes_radios.html\'>Checkboxes &amp; radios</a></li>");
document.writeln("										<li><a href=\'form_input_groups.html\'>Input groups</a></li>");
document.writeln("										<li><a href=\'form_controls_extended.html\'>Extended controls</a></li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Selects</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'form_select2.html\'>Select2 selects</a></li>");
document.writeln("												<li><a href=\'form_multiselect.html\'>Bootstrap multiselect</a></li>");
document.writeln("												<li><a href=\'form_select_box_it.html\'>SelectBoxIt selects</a></li>");
document.writeln("												<li><a href=\'form_bootstrap_select.html\'>Bootstrap selects</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li><a href=\'form_tag_inputs.html\'>Tag inputs</a></li>");
document.writeln("										<li><a href=\'form_dual_listboxes.html\'>Dual Listboxes</a></li>");
document.writeln("										<li><a href=\'form_editable.html\'>Editable forms</a></li>");
document.writeln("										<li><a href=\'form_validation.html\'>Validation</a></li>");
document.writeln("										<li><a href=\'form_inputs_grid.html\'>Inputs grid</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-footprint\'></i> <span>Wizards</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'wizard_steps.html\'>Steps wizard</a></li>");
document.writeln("										<li><a href=\'wizard_form.html\'>Form wizard</a></li>");
document.writeln("										<li><a href=\'wizard_stepy.html\'>Stepy wizard</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-spell-check\'></i> <span>Editors</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'editor_summernote.html\'>Summernote editor</a></li>");
document.writeln("										<li><a href=\'editor_ckeditor.html\'>CKEditor</a></li>");
document.writeln("										<li><a href=\'editor_wysihtml5.html\'>WYSIHTML5 editor</a></li>");
document.writeln("										<li><a href=\'editor_code.html\'>Code editor</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-select2\'></i> <span>Pickers</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'picker_date.html\'>Date &amp; time pickers</a></li>");
document.writeln("										<li><a href=\'picker_color.html\'>Color pickers</a></li>");
document.writeln("										<li><a href=\'picker_location.html\'>Location pickers</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-insert-template\'></i> <span>Form layouts</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'form_layout_vertical.html\'>Vertical form</a></li>");
document.writeln("										<li><a href=\'form_layout_horizontal.html\'>Horizontal form</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<!-- /forms -->");
document.writeln("");
document.writeln("								<!-- Appearance -->");
document.writeln("								<li class=\'navigation-header\'><span>Appearance</span> <i class=\'icon-menu\' title=\'Appearance\'></i></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-grid\'></i> <span>Components</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'components_modals.html\'>Modals</a></li>");
document.writeln("										<li><a href=\'components_dropdowns.html\'>Dropdown menus</a></li>");
document.writeln("										<li><a href=\'components_tabs.html\'>Tabs component</a></li>");
document.writeln("										<li><a href=\'components_pills.html\'>Pills component</a></li>");
document.writeln("										<li><a href=\'components_navs.html\'>Accordion and navs</a></li>");
document.writeln("										<li><a href=\'components_buttons.html\'>Buttons</a></li>");
document.writeln("										<li><a href=\'components_notifications_pnotify.html\'>PNotify notifications</a></li>");
document.writeln("										<li><a href=\'components_notifications_others.html\'>Other notifications</a></li>");
document.writeln("										<li><a href=\'components_popups.html\'>Tooltips and popovers</a></li>");
document.writeln("										<li><a href=\'components_alerts.html\'>Alerts</a></li>");
document.writeln("										<li><a href=\'components_pagination.html\'>Pagination</a></li>");
document.writeln("										<li><a href=\'components_labels.html\'>Labels and badges</a></li>");
document.writeln("										<li><a href=\'components_loaders.html\'>Loaders and bars</a></li>");
document.writeln("										<li><a href=\'components_thumbnails.html\'>Thumbnails</a></li>");
document.writeln("										<li><a href=\'components_page_header.html\'>Page header</a></li>");
document.writeln("										<li><a href=\'components_breadcrumbs.html\'>Breadcrumbs</a></li>");
document.writeln("										<li><a href=\'components_media.html\'>Media objects</a></li>");
document.writeln("										<li><a href=\'components_sliders.html\'>Slider components</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-puzzle2\'></i> <span>Content appearance</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'appearance_content_panels.html\'>Content panels</a></li>");
document.writeln("										<li><a href=\'appearance_panel_heading.html\'>Panel heading elements</a></li>");
document.writeln("										<li><a href=\'appearance_draggable_panels.html\'>Draggable panels</a></li>");
document.writeln("										<li><a href=\'appearance_text_styling.html\'>Text styling</a></li>");
document.writeln("										<li><a href=\'appearance_typography.html\'>Typography</a></li>");
document.writeln("										<li><a href=\'appearance_helpers.html\'>Helper classes</a></li>");
document.writeln("										<li><a href=\'appearance_syntax_highlighter.html\'>Syntax highlighter</a></li>");
document.writeln("										<li><a href=\'appearance_content_grid.html\'>Grid system</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li><a href=\'components_animations.html\'><i class=\'icon-spinner3 spinner\'></i> <span>CSS3 animations</span></a></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-gift\'></i> <span>Extra components</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'extra_affix.html\'>Affix and Scrollspy</a></li>");
document.writeln("										<li><a href=\'extra_session_timeout.html\'>Session timeout</a></li>");
document.writeln("										<li><a href=\'extra_idle_timeout.html\'>Idle timeout</a></li>");
document.writeln("										<li><a href=\'extra_trees.html\'>Dynamic tree views</a></li>");
document.writeln("										<li><a href=\'extra_context_menu.html\'>Context menu</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-thumbs-up2\'></i> <span>Icons</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'icons_glyphicons.html\'>Glyphicons</a></li>");
document.writeln("										<li><a href=\'icons_icomoon.html\'>Icomoon</a></li>");
document.writeln("										<li><a href=\'icons_fontawesome.html\'>Font awesome</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<!-- /appearance -->");
document.writeln("");
document.writeln("								<!-- Layout -->");
document.writeln("								<li class=\'navigation-header\'><span>Layout</span> <i class=\'icon-menu\' title=\'Layout options\'></i></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-indent-decrease2\'></i> <span>Sidebars</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'sidebar_default_collapse.html\'>Default collapsible</a></li>");
document.writeln("										<li><a href=\'sidebar_default_hide.html\'>Default hideable</a></li>");
document.writeln("										<li><a href=\'sidebar_mini_collapse.html\'>Mini collapsible</a></li>");
document.writeln("										<li><a href=\'sidebar_mini_hide.html\'>Mini hideable</a></li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Dual sidebar</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'sidebar_dual.html\'>Dual sidebar</a></li>");
document.writeln("												<li><a href=\'sidebar_dual_double_collapse.html\'>Dual double collapse</a></li>");
document.writeln("												<li><a href=\'sidebar_dual_double_hide.html\'>Dual double hide</a></li>");
document.writeln("												<li><a href=\'sidebar_dual_swap.html\'>Swap sidebars</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Double sidebar</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'sidebar_double_collapse.html\'>Collapse main sidebar</a></li>");
document.writeln("												<li><a href=\'sidebar_double_hide.html\'>Hide main sidebar</a></li>");
document.writeln("												<li><a href=\'sidebar_double_fix_default.html\'>Fix default width</a></li>");
document.writeln("												<li class=\'active\'><a href=\'sidebar_double_fix_mini.html\'>Fix mini width</a></li>");
document.writeln("												<li><a href=\'sidebar_double_visible.html\'>Opposite sidebar visible</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Detached sidebar</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'sidebar_detached_left.html\'>Left position</a></li>");
document.writeln("												<li><a href=\'sidebar_detached_right.html\'>Right position</a></li>");
document.writeln("												<li><a href=\'sidebar_detached_sticky_custom.html\'>Sticky (custom scroll)</a></li>");
document.writeln("												<li><a href=\'sidebar_detached_sticky_native.html\'>Sticky (native scroll)</a></li>");
document.writeln("												<li><a href=\'sidebar_detached_separate.html\'>Separate categories</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li><a href=\'sidebar_hidden.html\'>Hidden sidebar</a></li>");
document.writeln("										<li><a href=\'sidebar_light.html\'>Light sidebar</a></li>");
document.writeln("										<li><a href=\'sidebar_components.html\'>Sidebar components</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-sort\'></i> <span>Vertical navigation</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'navigation_vertical_collapsible.html\'>Collapsible menu</a></li>");
document.writeln("										<li><a href=\'navigation_vertical_accordion.html\'>Accordion menu</a></li>");
document.writeln("										<li><a href=\'navigation_vertical_sizing.html\'>Navigation sizing</a></li>");
document.writeln("										<li><a href=\'navigation_vertical_bordered.html\'>Bordered navigation</a></li>");
document.writeln("										<li><a href=\'navigation_vertical_right_icons.html\'>Right icons</a></li>");
document.writeln("										<li><a href=\'navigation_vertical_disabled.html\'>Disabled navigation links</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-transmission\'></i> <span>Horizontal navigation</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'navigation_horizontal_click.html\'>Submenu on click</a></li>");
document.writeln("										<li><a href=\'navigation_horizontal_hover.html\'>Submenu on hover</a></li>");
document.writeln("										<li><a href=\'navigation_horizontal_elements.html\'>With custom elements</a></li>");
document.writeln("										<li><a href=\'navigation_horizontal_tabs.html\'>Tabbed navigation</a></li>");
document.writeln("										<li><a href=\'navigation_horizontal_disabled.html\'>Disabled navigation links</a></li>");
document.writeln("										<li><a href=\'navigation_horizontal_mega.html\'>Horizontal mega menu</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-menu3\'></i> <span>Navbars</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'navbar_single.html\'>Single navbar</a></li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Multiple navbars</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'navbar_multiple_navbar_navbar.html\'>Navbar + navbar</a></li>");
document.writeln("												<li><a href=\'navbar_multiple_navbar_header.html\'>Navbar + header</a></li>");
document.writeln("												<li><a href=\'navbar_multiple_header_navbar.html\'>Header + navbar</a></li>");
document.writeln("												<li><a href=\'navbar_multiple_top_bottom.html\'>Top + bottom</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li><a href=\'navbar_colors.html\'>Color options</a></li>");
document.writeln("										<li><a href=\'navbar_sizes.html\'>Sizing options</a></li>");
document.writeln("										<li><a href=\'navbar_hideable.html\'>Hide on scroll</a></li>");
document.writeln("										<li><a href=\'navbar_components.html\'>Navbar components</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-tree5\'></i> <span>Menu levels</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'#\'><i class=\'icon-IE\'></i> Second level</a></li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'><i class=\'icon-firefox\'></i> Second level with child</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'#\'><i class=\'icon-android\'></i> Third level</a></li>");
document.writeln("												<li>");
document.writeln("													<a href=\'#\'><i class=\'icon-apple2\'></i> Third level with child</a>");
document.writeln("													<ul>");
document.writeln("														<li><a href=\'#\'><i class=\'icon-html5\'></i> Fourth level</a></li>");
document.writeln("														<li><a href=\'#\'><i class=\'icon-css3\'></i> Fourth level</a></li>");
document.writeln("													</ul>");
document.writeln("												</li>");
document.writeln("												<li><a href=\'#\'><i class=\'icon-windows\'></i> Third level</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li><a href=\'#\'><i class=\'icon-chrome\'></i> Second level</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<!-- /layout -->");
document.writeln("");
document.writeln("								<!-- Data visualization -->");
document.writeln("								<li class=\'navigation-header\'><span>Data visualization</span> <i class=\'icon-menu\' title=\'Data visualization\'></i></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-graph\'></i> <span>Echarts library</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'echarts_lines_areas.html\'>Lines and areas</a></li>");
document.writeln("										<li><a href=\'echarts_columns_waterfalls.html\'>Columns and waterfalls</a></li>");
document.writeln("										<li><a href=\'echarts_bars_tornados.html\'>Bars and tornados</a></li>");
document.writeln("										<li><a href=\'echarts_scatter.html\'>Scatter charts</a></li>");
document.writeln("										<li><a href=\'echarts_pies_donuts.html\'>Pies and donuts</a></li>");
document.writeln("										<li><a href=\'echarts_funnels_chords.html\'>Funnels and chords</a></li>");
document.writeln("										<li><a href=\'echarts_candlesticks_others.html\'>Candlesticks and others</a></li>");
document.writeln("										<li><a href=\'echarts_combinations.html\'>Chart combinations</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-statistics\'></i> <span>D3 library</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'d3_lines_basic.html\'>Simple lines</a></li>");
document.writeln("										<li><a href=\'d3_lines_advanced.html\'>Advanced lines</a></li>");
document.writeln("										<li><a href=\'d3_bars_basic.html\'>Simple bars</a></li>");
document.writeln("										<li><a href=\'d3_bars_advanced.html\'>Advanced bars</a></li>");
document.writeln("										<li><a href=\'d3_pies.html\'>Pie charts</a></li>");
document.writeln("										<li><a href=\'d3_circle_diagrams.html\'>Circle diagrams</a></li>");
document.writeln("										<li><a href=\'d3_tree.html\'>Tree layout</a></li>");
document.writeln("										<li><a href=\'d3_other.html\'>Other charts</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-stats-dots\'></i> <span>Dimple library</span></a>");
document.writeln("									<ul>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Line charts</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'dimple_lines_horizontal.html\'>Horizontal orientation</a></li>");
document.writeln("												<li><a href=\'dimple_lines_vertical.html\'>Vertical orientation</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Bar charts</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'dimple_bars_horizontal.html\'>Horizontal orientation</a></li>");
document.writeln("												<li><a href=\'dimple_bars_vertical.html\'>Vertical orientation</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Area charts</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'dimple_area_horizontal.html\'>Horizontal orientation</a></li>");
document.writeln("												<li><a href=\'dimple_area_vertical.html\'>Vertical orientation</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Step charts</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'dimple_step_horizontal.html\'>Horizontal orientation</a></li>");
document.writeln("												<li><a href=\'dimple_step_vertical.html\'>Vertical orientation</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li><a href=\'dimple_pies.html\'>Pie charts</a></li>");
document.writeln("										<li><a href=\'dimple_rings.html\'>Ring charts</a></li>");
document.writeln("										<li><a href=\'dimple_scatter.html\'>Scatter charts</a></li>");
document.writeln("										<li><a href=\'dimple_bubble.html\'>Bubble charts</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-stats-bars\'></i> <span>C3 library</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'c3_lines_areas.html\'>Lines and areas</a></li>");
document.writeln("										<li><a href=\'c3_bars_pies.html\'>Bars and pies</a></li>");
document.writeln("										<li><a href=\'c3_advanced.html\'>Advanced examples</a></li>");
document.writeln("										<li><a href=\'c3_axis.html\'>Chart axis</a></li>");
document.writeln("										<li><a href=\'c3_grid.html\'>Grid options</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-google\'></i> <span>Google visualization</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'google_lines.html\'>Line charts</a></li>");
document.writeln("										<li><a href=\'google_bars.html\'>Bar charts</a></li>");
document.writeln("										<li><a href=\'google_pies.html\'>Pie charts</a></li>");
document.writeln("										<li><a href=\'google_scatter_bubble.html\'>Bubble &amp; scatter charts</a></li>");
document.writeln("										<li><a href=\'google_other.html\'>Other charts</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-map5\'></i> <span>Maps integration</span></a>");
document.writeln("									<ul>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>Google maps</a>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'maps_google_basic.html\'>Basics</a></li>");
document.writeln("												<li><a href=\'maps_google_controls.html\'>Controls</a></li>");
document.writeln("												<li><a href=\'maps_google_markers.html\'>Markers</a></li>");
document.writeln("												<li><a href=\'maps_google_drawings.html\'>Map drawings</a></li>");
document.writeln("												<li><a href=\'maps_google_layers.html\'>Layers</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li><a href=\'maps_vector.html\'>Vector maps</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<!-- /data visualization -->");
document.writeln("");
document.writeln("								<!-- Extensions -->");
document.writeln("								<li class=\'navigation-header\'><span>Extensions</span> <i class=\'icon-menu\' title=\'Extensions\'></i></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-spinner10 spinner\'></i> <span>Velocity animations</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'extension_velocity_basic.html\'>Basic usage</a></li>");
document.writeln("										<li><a href=\'extension_velocity_ui.html\'>UI pack effects</a></li>");
document.writeln("										<li><a href=\'extension_velocity_examples.html\'>Advanced examples</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li><a href=\'extension_blockui.html\'><i class=\'icon-history\'></i> <span>Block UI</span></a></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-upload\'></i> <span>File uploaders</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'uploader_plupload.html\'>Plupload</a></li>");
document.writeln("										<li><a href=\'uploader_bootstrap.html\'>Bootstrap file uploader</a></li>");
document.writeln("										<li><a href=\'uploader_dropzone.html\'>Dropzone</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li><a href=\'extension_image_cropper.html\'><i class=\'icon-crop2\'></i> <span>Image cropper</span></a></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-calendar3\'></i> <span>Event calendars</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'extension_fullcalendar_views.html\'>Basic views</a></li>");
document.writeln("										<li><a href=\'extension_fullcalendar_styling.html\'>Event styling</a></li>");
document.writeln("										<li><a href=\'extension_fullcalendar_formats.html\'>Language and time</a></li>");
document.writeln("										<li><a href=\'extension_fullcalendar_advanced.html\'>Advanced usage</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-sphere\'></i> <span>Internationalization</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'internationalization_switch_direct.html\'>Direct translation</a></li>");
document.writeln("										<li><a href=\'internationalization_switch_query.html\'>Querystring parameter</a></li>");
document.writeln("										<li><a href=\'internationalization_on_init.html\'>Set language on init</a></li>");
document.writeln("										<li><a href=\'internationalization_after_init.html\'>Set language after init</a></li>");
document.writeln("										<li><a href=\'internationalization_fallback.html\'>Language fallback</a></li>");
document.writeln("										<li><a href=\'internationalization_callbacks.html\'>Callbacks</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<!-- /extensions -->");
document.writeln("");
document.writeln("								<!-- Tables -->");
document.writeln("								<li class=\'navigation-header\'><span>Tables</span> <i class=\'icon-menu\' title=\'Tables\'></i></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-table2\'></i> <span>Basic tables</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'table_basic.html\'>Basic examples</a></li>");
document.writeln("										<li><a href=\'table_sizing.html\'>Table sizing</a></li>");
document.writeln("										<li><a href=\'table_borders.html\'>Table borders</a></li>");
document.writeln("										<li><a href=\'table_styling.html\'>Table styling</a></li>");
document.writeln("										<li><a href=\'table_elements.html\'>Table elements</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-grid7\'></i> <span>Data tables</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'datatable_basic.html\'>Basic initialization</a></li>");
document.writeln("										<li><a href=\'datatable_styling.html\'>Basic styling</a></li>");
document.writeln("										<li><a href=\'datatable_advanced.html\'>Advanced examples</a></li>");
document.writeln("										<li><a href=\'datatable_sorting.html\'>Sorting options</a></li>");
document.writeln("										<li><a href=\'datatable_api.html\'>Using API</a></li>");
document.writeln("										<li><a href=\'datatable_data_sources.html\'>Data sources</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-alignment-unalign\'></i> <span>Data tables extensions</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'datatable_extension_reorder.html\'>Columns reorder</a></li>");
document.writeln("										<li><a href=\'datatable_extension_fixed_columns.html\'>Fixed columns</a></li>");
document.writeln("										<li><a href=\'datatable_extension_colvis.html\'>Columns visibility</a></li>");
document.writeln("										<li><a href=\'datatable_extension_tools.html\'>Table tools</a></li>");
document.writeln("										<li><a href=\'datatable_extension_scroller.html\'>Scroller</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-versions\'></i> <span>Responsive options</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'table_responsive.html\'>Responsive basic tables</a></li>");
document.writeln("										<li><a href=\'datatable_responsive.html\'>Responsive data tables</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<!-- /tables -->");
document.writeln("");
document.writeln("								<!-- Page kits -->");
document.writeln("								<li class=\'navigation-header\'><span>Page kits</span> <i class=\'icon-menu\' title=\'Page kits\'></i></li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-task\'></i> <span>Task manager</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'task_manager_grid.html\'>Task grid</a></li>");
document.writeln("										<li><a href=\'task_manager_list.html\'>Task list</a></li>");
document.writeln("										<li><a href=\'task_manager_detailed.html\'>Task detailed</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-cash3\'></i> <span>Invoicing</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'invoice_template.html\'>Invoice template</a></li>");
document.writeln("										<li><a href=\'invoice_grid.html\'>Invoice grid</a></li>");
document.writeln("										<li><a href=\'invoice_archive.html\'>Invoice archive</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-people\'></i> <span>User pages</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'user_pages_cards.html\'>User cards</a></li>");
document.writeln("										<li><a href=\'user_pages_list.html\'>User list</a></li>");
document.writeln("										<li><a href=\'user_pages_profile.html\'>Simple profile</a></li>");
document.writeln("										<li><a href=\'user_pages_profile_cover.html\'>Profile with cover</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-user-plus\'></i> <span>Login &amp; registration</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'login_simple.html\'>Simple login</a></li>");
document.writeln("										<li><a href=\'login_advanced.html\'>More login info</a></li>");
document.writeln("										<li><a href=\'login_registration.html\'>Simple registration</a></li>");
document.writeln("										<li><a href=\'login_registration_advanced.html\'>More registration info</a></li>");
document.writeln("										<li><a href=\'login_unlock.html\'>Unlock user</a></li>");
document.writeln("										<li><a href=\'login_password_recover.html\'>Reset password</a></li>");
document.writeln("										<li><a href=\'login_hide_navbar.html\'>Hide navbar</a></li>");
document.writeln("										<li><a href=\'login_transparent.html\'>Transparent box</a></li>");
document.writeln("										<li><a href=\'login_background.html\'>Background option</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-magazine\'></i> <span>Timelines</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'timelines_left.html\'>Left timeline</a></li>");
document.writeln("										<li><a href=\'timelines_right.html\'>Right timeline</a></li>");
document.writeln("										<li><a href=\'timelines_center.html\'>Centered timeline</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-lifebuoy\'></i> <span>Support</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'support_conversation_layouts.html\'>Conversation layouts</a></li>");
document.writeln("										<li><a href=\'support_conversation_options.html\'>Conversation options</a></li>");
document.writeln("										<li><a href=\'support_knowledgebase.html\'>Knowledgebase</a></li>");
document.writeln("										<li><a href=\'support_faq.html\'>FAQ page</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-search4\'></i> <span>Search</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'search_basic.html\'>Basic search results</a></li>");
document.writeln("										<li><a href=\'search_users.html\'>User search results</a></li>");
document.writeln("										<li><a href=\'search_images.html\'>Image search results</a></li>");
document.writeln("										<li><a href=\'search_videos.html\'>Video search results</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-images2\'></i> <span>Gallery</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'gallery_grid.html\'>Media grid</a></li>");
document.writeln("										<li><a href=\'gallery_titles.html\'>Media with titles</a></li>");
document.writeln("										<li><a href=\'gallery_description.html\'>Media with description</a></li>");
document.writeln("										<li><a href=\'gallery_library.html\'>Media library</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'><i class=\'icon-warning\'></i> <span>Error pages</span></a>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'error_403.html\'>Error 403</a></li>");
document.writeln("										<li><a href=\'error_404.html\'>Error 404</a></li>");
document.writeln("										<li><a href=\'error_405.html\'>Error 405</a></li>");
document.writeln("										<li><a href=\'error_500.html\'>Error 500</a></li>");
document.writeln("										<li><a href=\'error_503.html\'>Error 503</a></li>");
document.writeln("										<li><a href=\'error_offline.html\'>Offline page</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<!-- /page kits -->");
document.writeln("");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<!-- /main navigation -->");
document.writeln("");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<!-- /main sidebar -->");