document.writeln("			<!-- Main sidebar -->");
document.writeln("			<div class=\'sidebar sidebar-main\'>");
document.writeln("				<div class=\'sidebar-content\'>");
document.writeln("");
document.writeln("					<!-- User menu -->");
document.writeln("					<div class=\'sidebar-user\'>");
document.writeln("						<div class=\'category-content\'>");
document.writeln("							<div class=\'media\'>");
document.writeln("								<a href=\'#\' class=\'media-left\'><img src=\'/static/assets/images/placeholder.jpg\' class=\'img-circle img-sm\' alt=\'\'></a>");
document.writeln("								<div class=\'media-body\'>");
document.writeln("									<span class=\'media-heading text-semibold\'>Victoria Baker</span>");
document.writeln("									<div class=\'text-size-mini text-muted\'>");
document.writeln("										<i class=\'icon-pin text-size-small\'></i> &nbsp;Santa Ana, CA");
document.writeln("									</div>");
document.writeln("								</div>");
document.writeln("");
document.writeln("								<div class=\'media-right media-middle\'>");
document.writeln("									<ul class=\'icons-list\'>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'><i class=\'icon-cog3\'></i></a>");
document.writeln("										</li>");
document.writeln("									</ul>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<!-- /user menu -->");
document.writeln("");
document.writeln("");
document.writeln("					<!-- Main navigation -->");
document.writeln("					<div class=\'sidebar-category sidebar-category-visible\'>");
document.writeln("						<div class=\'category-content no-padding\'>");
document.writeln("							<ul class=\'navigation navigation-main navigation-accordion\'>");
document.writeln("");
document.writeln("								<!-- Main -->");
document.writeln("								<li><a href=\'/\'><i class=\'icon-home4\'></i> <span>主页</span></a></li>");
document.writeln("								<li><a href=\'industries\'><i class=\'icon-stack2\'></i> <span>行业分析</span></a></li>");
document.writeln("								<li class=\'navigation-header\'><span>个股分析</span> <i class=\'icon-menu\' title=\'个股分析\'></i></li>");
document.writeln("								<li class=\'navigation-header\'><span>数据管理</span> <i class=\'icon-menu\' title=\'数据管理\'></i></li>");
document.writeln("");			
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<!-- /main navigation -->");
document.writeln("");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<!-- /main sidebar -->");